### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by acgmohu** [CalebFenton/dex-oracle#1]
Hi caleb,

My dex-oracle could not work. Could you help me?
I have not idea about these msg.
```
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [i386-linux-gnu]
$ gem -v
2.5.1
$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using ast 2.2.0
Using rubyzip 1.1.7
Using diff-lcs 1.2.5
Using powerpack 0.1.1
Using rainbow 2.1.0
Using rspec-support 3.4.1
Using ruby-progressbar 1.7.5
Using unicode-display_width 0.3.1
Using bundler 1.11.2
Using parser 2.3.0.6
Using dex-oracle 1.0.3 from source at `.`
Using rspec-core 3.4.2
Using rspec-expectations 3.4.0
Using rspec-mocks 3.4.1
Using rubocop 0.37.2
Using rspec-its 1.2.0
Installing rspec 3.4.0
Bundle complete! 5 Gemfile dependencies, 17 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

$ ./bin/dex-oracle 
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- Open3 (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/lai/github/dex-oracle/lib/dex-oracle/driver.rb:3:in `<top (required)>'
	from ./bin/dex-oracle:6:in `require_relative'
	from ./bin/dex-oracle:6:in `<main>'
```

**Comment by CalebFenton** [comment]
Thanks for the detailed error report!

Any chance you could build and test from the repo? I believe the issue was fixed with https://github.com/CalebFenton/dex-oracle/commit/467b66bad8d33e4609fc6427e6695b7f052ffca6 but I'd like confirmation before uploading a new rubygems version.

If you can't, that's fine. I'll test it myself on Linux a little later.

**Comment by strazzere** [comment]
Confirmed on a fresh ubuntu install

```
diff@ubuntu:~/repo/dex-oracle$ uname -a
Linux ubuntu 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
diff@ubuntu:~/repo/dex-oracle$ ruby -v
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
diff@ubuntu:~/repo/dex-oracle$ gem -v
2.2.2
diff@ubuntu:~/repo/dex-oracle$ ./bin/dex-oracle 
Usage: dex-oracle [opts] <APK / DEX / Smali Directory>
    -h, --help                       Display this screen
    -s ANDROID_SERIAL,               Device ID for driver execution, default=""
        --specific-device
    -t, --timeout N                  ADB command execution timeout in seconds, default="120"
    -i, --include PATTERN            Only optimize methods and classes matching the pattern, e.g. Ldune;->melange\(\)V
    -e, --exclude PATTERN            Exclude these types from optimization; including overrides
        --disable-plugins STRING[,STRING]*
                                     Disable plugins, e.g. stringdecryptor,unreflector
        --list-plugins               List available plugins
    -v, --verbose                    Be verbose
    -V, --vverbose                   Be very verbose
```

**Comment by acgmohu** [comment]
Thanks very much. Now it work!
```
$ uname -a
Linux lai-virtual-machine 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:37:25 UTC 2015 i686 i686 i686 GNU/Linux

$ ./bin/dex-oracle 
Usage: dex-oracle [opts] <APK / DEX / Smali Directory>
    -h, --help                       Display this screen
    -s ANDROID_SERIAL,               Device ID for driver execution, default=""
        --specific-device
    -t, --timeout N                  ADB command execution timeout in seconds, default="120"
    -i, --include PATTERN            Only optimize methods and classes matching the pattern, e.g. Ldune;->melange\(\)V
    -e, --exclude PATTERN            Exclude these types from optimization; including overrides
        --disable-plugins STRING[,STRING]*
                                     Disable plugins, e.g. stringdecryptor,unreflector
        --list-plugins               List available plugins
    -v, --verbose                    Be verbose
    -V, --vverbose                   Be very verbose

```
