### ISSUE TITLE
Command failed

### ISSUE THREAD

**Issue by ddzobov** [CalebFenton/dex-oracle#29]
```
Optimizing 10575 methods over 1303 Smali files.
**/dex-oracle/lib/dex-oracle/driver.rb:190:in `validate_output': Command failed with 255: shell "cd /data/local/tmp; export CLASSPATH=/data/local/tmp/od.zip; app_process /system/bin org.cf.oracle.Driver @/data/local/tmp/od-targets.json"; echo $? (RuntimeError)
Output: 255
	from **/dex-oracle/lib/dex-oracle/driver.rb:208:in `drive'
	from **/dex-oracle/lib/dex-oracle/driver.rb:96:in `run_batch'
	from **/dex-oracle/lib/dex-oracle/plugin.rb:49:in `apply_batch'
	from **/dex-oracle/lib/dex-oracle/plugins/string_decryptor.rb:38:in `process'
	from **/dex-oracle/lib/oracle.rb:33:in `block (2 levels) in process_plugins'
	from **/dex-oracle/lib/oracle.rb:31:in `each'
	from **/dex-oracle/lib/oracle.rb:31:in `block in process_plugins'
	from **/dex-oracle/lib/oracle.rb:29:in `loop'
	from **/dex-oracle/lib/oracle.rb:29:in `process_plugins'
	from **/dex-oracle/lib/oracle.rb:18:in `divine'
	from ./dex-oracle/bin/dex-oracle:98:in `<main>'
```

**Comment by ddzobov** [comment]
Installed Android 5 emulator

`**/dex-oracle/lib/dex-oracle/driver.rb:198:in `validate_output': app_process execution failure, output: '0' (RuntimeError)`

**Comment by CalebFenton** [comment]
Could you share the sample and command line you're using?

**Comment by ddzobov** [comment]
Sent to you yesterday by email

**Comment by ddzobov** [comment]
Can you confirm that you received sample from me by email?

**Comment by CalebFenton** [comment]
I got it, but the tiny startup company I use for email doesn't know how to handle multiple users and I had to request access using another account.

**Comment by ddzobov** [comment]
Hi! Are you received access to file?

**Comment by CalebFenton** [comment]
I haven't had time to look into it. You can help yourself by running with verbose mode on, watching exactly what dex-oracle does, and do it youself on the command line. All the code does is coordinate some stuff on the command line (and make it easy to reflect methods with the driver).
