### ISSUE TITLE
Crap, smali compilation failed. (RuntimeError)

### ISSUE THREAD

**Issue by uceka** [CalebFenton/dex-oracle#30]
Hi, i got an issue. Please follow the code;

dex-oracle  dex_2767.dex --disable-plugins bitwiseantiskid,stringdecryptor,undexguard,unreflector,indexedclasslookup -i '/d'

`
Exception in thread "main" com.beust.jcommander.MissingCommandException: Expected a command, got dex_2767.dex
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:725)
	at com.beust.jcommander.JCommander.parse(JCommander.java:304)
	at com.beust.jcommander.JCommander.parse(JCommander.java:287)
	at org.jf.baksmali.Main.main(Main.java:90)
Optimizing 0 methods over 0 Smali files.
Optimizations:
Exception in thread "main" com.beust.jcommander.MissingCommandException: Expected a command, got /var/folders/25/3661xv3s1s38s523pmbz27300000gn/T/d20190115-6948-1rg4wpm
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:725)
	at com.beust.jcommander.JCommander.parse(JCommander.java:304)
	at com.beust.jcommander.JCommander.parse(JCommander.java:287)
	at org.jf.smali.Main.main(Main.java:87)
/Users/uceka/.rvm/gems/ruby-2.3.0/gems/dex-oracle-1.0.5/lib/dex-oracle/smali_input.rb:30:in `compile': Crap, smali compilation failed. (RuntimeError)
	from /Users/uceka/.rvm/gems/ruby-2.3.0/gems/dex-oracle-1.0.5/lib/dex-oracle/smali_input.rb:19:in `finish'
	from /Users/uceka/.rvm/gems/ruby-2.3.0/gems/dex-oracle-1.0.5/bin/dex-oracle:96:in `<top (required)>'
	from /Users/uceka/.rvm/gems/ruby-2.3.0/bin/dex-oracle:23:in `load'
	from /Users/uceka/.rvm/gems/ruby-2.3.0/bin/dex-oracle:23:in `<main>'
	from /Users/uceka/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/uceka/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'`
`

**Comment by CalebFenton** [comment]
Could you try installing the gem from source? The problem is the cli for baksmali changed, I think.

I think I just need to update the gem if that fixes the issue.
