### ISSUE TITLE
Error /var/lib/gems/2.7.0/gems/dex-oracle-1.0.5/lib/dex-oracle/smali_input.rb:66:in `initialize': No such file or directory

### ISSUE THREAD

**Issue by SlxshModder** [CalebFenton/dex-oracle#37]
Help me i have this error when i use it

dex-oracle class/a/b/c test.apk
Traceback (most recent call last):
        7: from /usr/local/bin/dex-oracle:23:in `<main>'
        6: from /usr/local/bin/dex-oracle:23:in `load'
        5: from /var/lib/gems/2.7.0/gems/dex-oracle-1.0.5/bin/dex-oracle:86:in `<top (required)>'
        4: from /var/lib/gems/2.7.0/gems/dex-oracle-1.0.5/bin/dex-oracle:86:in `new'
        3: from /var/lib/gems/2.7.0/gems/dex-oracle-1.0.5/lib/dex-oracle/smali_input.rb:14:in `initialize'
        2: from /var/lib/gems/2.7.0/gems/dex-oracle-1.0.5/lib/dex-oracle/smali_input.rb:66:in `prepare'
        1: from /var/lib/gems/2.7.0/gems/dex-oracle-1.0.5/lib/dex-oracle/smali_input.rb:66:in `open'
/var/lib/gems/2.7.0/gems/dex-oracle-1.0.5/lib/dex-oracle/smali_input.rb:66:in `initialize': No such file or directory @ rb_sysopen - class/a/b/c (Errno::ENOENT)

**Comment by SlxshModder** [comment]
help me
