### ISSUE TITLE
Ruby Zipfile trying to rename open Tempfile

### ISSUE THREAD

**Issue by CalebFenton** [CalebFenton/dex-oracle#5]
Windows is currently broken because an open Tempfile is given to Zip to create a new zip.

Error looks like this:
```
C:\repos\dex-oracle>ruby bin\dex-oracle -v app.apk
Error installing driver: Permission denied @ rb_file_s_rename - (C:/Users/devbox/AppData/Local/Temp/oracle-driver20160709-1628-1n79sw2.zip20160709-1628-n6l3hq,C:/Users/devbox/AppData/Local/Temp/oracle-driver20160709-1628-1n79sw2.zip)
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/file.rb:408:in `rename'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/file.rb:408:in `on_success_replace'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/file.rb:310:in `commit'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/file.rb:334:in `close'
        C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubyzip-1.2.0/lib/zip/file.rb:104:in `open'
        C:/repos/dex-oracle/lib/dex-oracle/utility.rb:16:in `create_zip'
        C:/repos/dex-oracle/lib/dex-oracle/driver.rb:53:in `install'
        bin/dex-oracle:89:in `<main>'
C:/repos/dex-oracle/lib/dex-oracle/smali_file.rb:42:in `read': Invalid argument @ rb_sysopen - C:/Users/devbox/AppData/Local/Temp/d20160709-1628-14kgu8g/com/android/volley/toolbox/????.smali (Errno::EINVAL)
        from C:/repos/dex-oracle/lib/dex-oracle/smali_file.rb:42:in `parse'
        from C:/repos/dex-oracle/lib/dex-oracle/smali_file.rb:21:in `initialize'
        from C:/repos/dex-oracle/lib/oracle.rb:58:in `new'
        from C:/repos/dex-oracle/lib/oracle.rb:58:in `block in parse_smali'
        from C:/repos/dex-oracle/lib/oracle.rb:58:in `each'
        from C:/repos/dex-oracle/lib/oracle.rb:58:in `parse_smali'
        from C:/repos/dex-oracle/lib/oracle.rb:9:in `initialize'
        from bin/dex-oracle:91:in `new'
        from bin/dex-oracle:91:in `<main>'
```

**Comment by CalebFenton** [comment]
Fixed in https://github.com/CalebFenton/dex-oracle/commit/af5f5072765c07e6cb3be54534806b94d1d5dcb8
