### ISSUE TITLE
Windows fails to handle filenames with unicode characters

### ISSUE THREAD

**Issue by CalebFenton** [CalebFenton/dex-oracle#6]
Filenames with unicode characters are completely borked.

Error looks like:
```
C:/repos/dex-oracle/lib/dex-oracle/smali_file.rb:42:in `read': Invalid argument @ rb_sysopen - C:/Users/devbox/AppData/Local/Temp/d20160709-1872-zlz4qx/com/android/volley/toolbox/????.smali (Errno::EINVAL)
        from C:/repos/dex-oracle/lib/dex-oracle/smali_file.rb:42:in `parse'
        from C:/repos/dex-oracle/lib/dex-oracle/smali_file.rb:21:in `initialize'
        from C:/repos/dex-oracle/lib/oracle.rb:58:in `new'
        from C:/repos/dex-oracle/lib/oracle.rb:58:in `block in parse_smali'
        from C:/repos/dex-oracle/lib/oracle.rb:58:in `each'
        from C:/repos/dex-oracle/lib/oracle.rb:58:in `parse_smali'
        from C:/repos/dex-oracle/lib/oracle.rb:9:in `initialize'
        from bin/dex-oracle:91:in `new'
        from bin/dex-oracle:91:in `<main>'
```

**Comment by CalebFenton** [comment]
Fixed in https://github.com/CalebFenton/dex-oracle/commit/46918547baf7ee9393ec7328dc895be460a95bf6
