### ISSUE TITLE
Which version of Ruby is required?

### ISSUE THREAD

**Issue by Disane** [CalebFenton/dex-oracle#7]
Hi,

I'm having trouble figuring out which version of Ruby is being used to run dex-oracle. Could you help me by revealing this information?

Here's what I tried: I followed your instructions. Grabbed, installed and exported smali, baksmali, etc. I already had an AVD setup as well as the Android SDK. Here's what happened when I tried to make use of dex-oracle:

```
// Tried this (I have the Obad sample mentioned in the instructions):
disane@ubuntu:~/Desktop$ dex-oracle -i com/android/system/admin/CCOIoll /mnt/hgfs/VMWareShared/obad.apk 
// Uploading APK to started AVD
2982 KB/s (241347 bytes in 0.079s)
// Then an error is yielded by the Ruby interpreter:
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /var/lib/gems/1.9.1/gems/dex-oracle-1.0.5/lib/dex-oracle/plugins/undexguard.rb:52: syntax error, unexpected tLPAREN_ARG, expecting keyword_do_LAMBDA or tLAMBEG (SyntaxError)
  MODIFIER = -> (_, output, out_reg) { "const-...
                 ^
/var/lib/gems/1.9.1/gems/dex-oracle-1.0.5/lib/dex-oracle/plugins/undexguard.rb:52: syntax error, unexpected ')', expecting '='
...IFIER = -> (_, output, out_reg) { "const-string #{out_reg}, ...
...                               ^
/var/lib/gems/1.9.1/gems/dex-oracle-1.0.5/lib/dex-oracle/plugins/undexguard.rb:52: syntax error, unexpected '}', expecting keyword_end
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.5/lib/dex-oracle/plugin.rb:16:in `block in plugin_classes'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.5/lib/dex-oracle/plugin.rb:16:in `each'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.5/lib/dex-oracle/plugin.rb:16:in `plugin_classes'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.5/lib/dex-oracle/plugin.rb:28:in `init_plugins'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.5/lib/oracle.rb:11:in `initialize'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.5/bin/dex-oracle:91:in `new'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.5/bin/dex-oracle:91:in `<top (required)>'
	from /usr/local/bin/dex-oracle:23:in `load'
	from /usr/local/bin/dex-oracle:23:in `<main>'
```

Also when I tried to list all mentioned dex-oracle plugins I get the following error:
```
disane@ubuntu:~/Desktop$ dex-oracle --list-plugins
Available plugins:
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /var/lib/gems/1.9.1/gems/dex-oracle-1.0.5/lib/dex-oracle/plugins/undexguard.rb:52: syntax error, unexpected tLPAREN_ARG, expecting keyword_do_LAMBDA or tLAMBEG (SyntaxError)
  MODIFIER = -> (_, output, out_reg) { "const-...
                 ^
/var/lib/gems/1.9.1/gems/dex-oracle-1.0.5/lib/dex-oracle/plugins/undexguard.rb:52: syntax error, unexpected ')', expecting '='
...IFIER = -> (_, output, out_reg) { "const-string #{out_reg}, ...
...                               ^
/var/lib/gems/1.9.1/gems/dex-oracle-1.0.5/lib/dex-oracle/plugins/undexguard.rb:52: syntax error, unexpected '}', expecting keyword_end
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.5/lib/dex-oracle/plugin.rb:16:in `block in plugin_classes'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.5/lib/dex-oracle/plugin.rb:16:in `each'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.5/lib/dex-oracle/plugin.rb:16:in `plugin_classes'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.5/bin/dex-oracle:55:in `block (2 levels) in <top (required)>'
	from /usr/lib/ruby/1.9.1/optparse.rb:1360:in `call'
	from /usr/lib/ruby/1.9.1/optparse.rb:1360:in `block in parse_in_order'
	from /usr/lib/ruby/1.9.1/optparse.rb:1347:in `catch'
	from /usr/lib/ruby/1.9.1/optparse.rb:1347:in `parse_in_order'
	from /usr/lib/ruby/1.9.1/optparse.rb:1341:in `order!'
	from /usr/lib/ruby/1.9.1/optparse.rb:1432:in `permute!'
	from /usr/lib/ruby/1.9.1/optparse.rb:1453:in `parse!'
	from /var/lib/gems/1.9.1/gems/dex-oracle-1.0.5/bin/dex-oracle:67:in `<top (required)>'
	from /usr/local/bin/dex-oracle:23:in `load'
	from /usr/local/bin/dex-oracle:23:in `<main>'
```

Looking at the features of the tool, it would seem useful for analyzing and RE-ing obfuscated Android Malware, but I need to know what kind of environment I need to setup to get it to work.

If the log is unreadable, I put up a copy on pastebin of both error messages:
http://pastebin.com/Y6NNg7nv

Regards,
Disane

**Comment by CalebFenton** [comment]
Thanks for the detailed error report.

I think I'm making use of some ruby 2.x syntax. Could you try with Ruby 2.x?

Also, if you have rvm installed, it would automatically setup the right ruby version because of this file here: https://github.com/CalebFenton/dex-oracle/blob/master/.ruby-version

**Comment by CalebFenton** [comment]
Closing because I'm pretty sure ruby 2.x will solve your issue.
